name: Freezzze
version: '1.0-SNAPSHOT'
main: me.weirdestboi.freezzze.Freezzze
author: WeirdestBoi
commands:
  freeze:
    description: Freeze A Player!
    permission: weirdestfreeze.freeze
  freezelist:
    description: List all Frozen Players!
    permission: weirdestfreeze.list
  freezereload:
    description: Reload the FreezePlugin!
    permission: weirdestfreeze.reload